### PR TITLE
Adds data count to the response

### PR DESCRIPTION
**Pull request by beauraines**
* appends the `dataCount` for $data that is countable and not empty
* Adds configuration
	* configurable label for dataCount, defaulting to "DATACOUNT"
	* optionally includes the dataCount, defaulting to false
* Updates to the README
	* Adds configuation sections
	* Adds information about matching Status codes (#16)
	* updates validation status code to 422 to match the changes introduced in fd90e10
	* Adds data count feature

### CODE REVIEW

**Comment by beauraines** [comment]
I'm not sure what the issues are with the styleci check... Let me know what I need to do to resolve that.

The CI build failed because of the tests that I updated in #23.  If you want, I could merge them into this PR first....

**Comment by obiefy** [comment]
Hi @beauraines, first of all thanks for you PRs.
There are issues in the test-cases we need to fix it first.
I'll work on it and make sure every thing is fine then I'll merge your PRs.
But first It will be great if you can follow the same coding style formatting, like 4 spaces for the tap.

**Comment by obiefy** [comment]
I was wondering how we can add `DATACOUNT` using our existing logic for extra data.
```php
 public function response($status, $message, $data, ...$extraData)
```

how we can use [`$extraData`](https://github.com/obiefy/api-response/blob/fbfcb1bd4953494745084014a0b9118f7a1a8de8/src/APIResponse.php#L30) parameter to get the same result.

**Comment by beauraines** [comment]
> There are issues in the test-cases we need to fix it first.

PR #23 which you merged will resolve the test cases. I'll rebase my branch from master and bring those updates in and that will get that check to pass.

> But first It will be great if you can follow the same coding style formatting, like 4 spaces for the tap.

Got it. I think my IDE just automatically made those changes for me. Good thing I didn't update more files. I'll get the formatting cleaned up.

**Comment by beauraines** [comment]
> I was wondering how we can add `DATACOUNT` using our existing logic for extra data.
> 
> ```
>  public function response($status, $message, $data, ...$extraData)
> ```
> 
> how we can use [`$extraData`](https://github.com/obiefy/api-response/blob/fbfcb1bd4953494745084014a0b9118f7a1a8de8/src/APIResponse.php#L30) parameter to get the same result.


I thought about this while making the change and this was my logic. I'd be happy to change it up however you think is best.

My concept was to put this on _every_ response, if the configuration was set. By making it part of the `$extraData`, you'd have to add it to every place you use the `response` function (by way of the helpers or otherwise).  We very well could write, with out any need for code change `return API::response(200, 'Users list', $users, ['dataCount'=>count($users)])` but you'd have to do that everywhere you made the call to that function. So, to avoid that, I went the configuration route.

I also considered adding a new parameter to `response($status, $message, $data, $displayCount, ...$extraData)` where `$displayCount` was a boolean, but that would be a breaking change to the `response()` function.

So, I was hoping to make the decision to add the new Response property _outside_ of the function call and in the configuration.

I could revise this statement

https://github.com/obiefy/api-response/blob/c803821c32c285c3f9d4a4b989189f66c3df7c91/src/APIResponse.php#L39-L40

to append its data to the `$extraData` so that the logic for appending `$extraData` to `$json` isn't "subverted".  I put it as a separate step so that it would always come _before_ the `$extraData`

Let me know what you think - this is your package, so I'll follow your lead. My objective was to add a configuration that would allow the developer to decide whether or not to get the count as part of all of their Responses. There are many ways to accomplish that!

**Comment by beauraines** [comment]
80e607f resolves the unit tests 

```
Beaus-MacBook-Pro:api-response beauraines$ git log --oneline -1
80e607f (HEAD -> add_data_count, origin/add_data_count) Merge branch 'add_data_count' of github.com:beauraines/api-response into add_data_count
Beaus-MacBook-Pro:api-response beauraines$ phpunit
PHPUnit 8.3.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.25 with Xdebug 2.8.0
Configuration: /Users/beauraines/projects/api-response/phpunit.xml

..................                                                18 / 18 (100%)

Time: 479 ms, Memory: 14.00 MB

OK (18 tests, 21 assertions)
```

**Comment by beauraines** [comment]
@obiefy Sorry about all those commits at the end. I didn't realize that StyleCI was actually giving me the diff to fix all my problems until my very last commit. I was just guessing at what the formatting problem was and 🤞 hoping that was the fix.


Let me know what you think about https://github.com/obiefy/api-response/pull/24#issuecomment-571291797

Thanks!

**Comment by obiefy** [comment]
OK @beauraines, let me check it as soon as I can and reply to you.
Thanks.

**Comment by obiefy** [comment]
Hi @beauraines, I'm really sorry for late reply.

**Comment by beauraines** [comment]
@obiefy I added 3 tests (the first tests I've written, BTW). Let me know what you think!

What is a good workflow to use with StyleCI so I _don't_ always have my code change commits and then the style fixes commits?

Thanks!

**Comment by obiefy** [comment]
I generally use my IDE configuration to match the project code formatting, I don't have a good idea of the best practice.

Thanks @beauraines for this PR.

**Pull request merged**
