### PR TITLE
Add support for extra data passed thru the response function

### PR DESCRIPTION
**Pull request by SamyOteroGlez**
The extra data can be added as a single array or as many arrays.
The extra data is recommended to be added as an array otherwise it will be added as `0 => data, 1 => data`.

Let me know if this works for you and if I can proceed to add the new feature to the rest of the responses functions such as ok(), validation(), etc

Cheers

### CODE REVIEW

**Comment by obiefy** [comment]
perfect, go ahead and finish it.

**Comment by SamyOteroGlez** [comment]
Ready to review

**Comment by obiefy** [comment]
Thanks, @SamyOteroGlez for the contribution.

**Comment by SamyOteroGlez** [comment]
More than welcome. Let me know if you need more help, I'll be happy to collaborate.

Cheers

**Comment by obiefy** [comment]
Really thanks a lot.
we only need to improve readme file to add some missing docs.
we have a lot of uncovered methods in the readme file. like developer can use `api()` helper directlly `api(201, 'Order created successfully', ['order'=> 'Order data']);`
If you can improve the readme docs, it will be great.
After that, we can release a new version.

Thanks.

**Pull request merged**
